name = "hammer_time"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["HammerTime"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "Hammer"
git = "https://github.com/JOSHCLUNE/LeanHammer"
rev = "v4.25.1"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.25.1"


[[lean_lib]]
name = "HammerTime"
