name = "cc_lean"
version = "0.1.0"
defaultTargets = ["cc_lean"]

[[lean_lib]]
name = "CcLean"

[[lean_lib]]
name = "Definitions"

[[lean_lib]]
name = "Base"

[[lean_lib]]
name = "Hammered"

[[lean_exe]]
name = "cc_lean"
root = "Main"

[[require]]
name = "Hammer"
git = "https://github.com/JOSHCLUNE/LeanHammer"
rev = "v4.25.2"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.25.2"
